name: build dotnet

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - dev/dotnet/**

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  push:
    name: "dotnet:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '6'
          - '6-sdk'
          - '7'
          - '7-sdk'
          - '8'
          - '8-sdk'
          - '9'
          - '9-sdk'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./dev/dotnet
          file: ./dev/dotnet/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/vwcompu/dotnet:${{ matrix.tag }}
